server:
  port: ${PORT:8082}

spring:
  application:
    name: catalogue-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:dbuser}:${MONGO_PASSWORD:dbpassword}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/catalogue